version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brh-visual-account
    restart: always
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://ntw_saas_brhunter:Ntw@27719#BRHunter@localhost:5444/br_hunter
      - DATABASE_HOST=localhost
      - DATABASE_NAME=br_hunter
      - DATABASE_USER=ntw_saas_brhunter
      - DATABASE_PASSWORD=Ntw@27719#BRHunter
      - DATABASE_PORT=5444
      - JWT_SECRET=brh-super-secret-key-2026-mude-em-producao!
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
