/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CondominiosRouteImport } from './routes/condominios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsuariosIndexRouteImport } from './routes/usuarios.index'
import { Route as PrestacoesIndexRouteImport } from './routes/prestacoes.index'
import { Route as UsuariosNovoRouteImport } from './routes/usuarios.novo'
import { Route as PrestacoesNovaRouteImport } from './routes/prestacoes.nova'
import { Route as PrestacoesIdEditarRouteImport } from './routes/prestacoes.$id.editar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CondominiosRoute = CondominiosRouteImport.update({
  id: '/condominios',
  path: '/condominios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosIndexRoute = UsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestacoesIndexRoute = PrestacoesIndexRouteImport.update({
  id: '/prestacoes/',
  path: '/prestacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosNovoRoute = UsuariosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => UsuariosRoute,
} as any)
const PrestacoesNovaRoute = PrestacoesNovaRouteImport.update({
  id: '/prestacoes/nova',
  path: '/prestacoes/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestacoesIdEditarRoute = PrestacoesIdEditarRouteImport.update({
  id: '/prestacoes/$id/editar',
  path: '/prestacoes/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/condominios': typeof CondominiosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/historico': typeof HistoricoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/prestacoes/nova': typeof PrestacoesNovaRoute
  '/usuarios/novo': typeof UsuariosNovoRoute
  '/prestacoes/': typeof PrestacoesIndexRoute
  '/usuarios/': typeof UsuariosIndexRoute
  '/prestacoes/$id/editar': typeof PrestacoesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/condominios': typeof CondominiosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/historico': typeof HistoricoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/prestacoes/nova': typeof PrestacoesNovaRoute
  '/usuarios/novo': typeof UsuariosNovoRoute
  '/prestacoes': typeof PrestacoesIndexRoute
  '/usuarios': typeof UsuariosIndexRoute
  '/prestacoes/$id/editar': typeof PrestacoesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/condominios': typeof CondominiosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/historico': typeof HistoricoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/prestacoes/nova': typeof PrestacoesNovaRoute
  '/usuarios/novo': typeof UsuariosNovoRoute
  '/prestacoes/': typeof PrestacoesIndexRoute
  '/usuarios/': typeof UsuariosIndexRoute
  '/prestacoes/$id/editar': typeof PrestacoesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/condominios'
    | '/configuracoes'
    | '/dashboard'
    | '/esqueci-senha'
    | '/historico'
    | '/home'
    | '/login'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/prestacoes/nova'
    | '/usuarios/novo'
    | '/prestacoes/'
    | '/usuarios/'
    | '/prestacoes/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/condominios'
    | '/configuracoes'
    | '/dashboard'
    | '/esqueci-senha'
    | '/historico'
    | '/home'
    | '/login'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/prestacoes/nova'
    | '/usuarios/novo'
    | '/prestacoes'
    | '/usuarios'
    | '/prestacoes/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/condominios'
    | '/configuracoes'
    | '/dashboard'
    | '/esqueci-senha'
    | '/historico'
    | '/home'
    | '/login'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/prestacoes/nova'
    | '/usuarios/novo'
    | '/prestacoes/'
    | '/usuarios/'
    | '/prestacoes/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CondominiosRoute: typeof CondominiosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  HistoricoRoute: typeof HistoricoRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PrestacoesNovaRoute: typeof PrestacoesNovaRoute
  PrestacoesIndexRoute: typeof PrestacoesIndexRoute
  UsuariosIndexRoute: typeof UsuariosIndexRoute
  PrestacoesIdEditarRoute: typeof PrestacoesIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condominios': {
      id: '/condominios'
      path: '/condominios'
      fullPath: '/condominios'
      preLoaderRoute: typeof CondominiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/': {
      id: '/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof UsuariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestacoes/': {
      id: '/prestacoes/'
      path: '/prestacoes'
      fullPath: '/prestacoes/'
      preLoaderRoute: typeof PrestacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/novo': {
      id: '/usuarios/novo'
      path: '/novo'
      fullPath: '/usuarios/novo'
      preLoaderRoute: typeof UsuariosNovoRouteImport
      parentRoute: typeof UsuariosRoute
    }
    '/prestacoes/nova': {
      id: '/prestacoes/nova'
      path: '/prestacoes/nova'
      fullPath: '/prestacoes/nova'
      preLoaderRoute: typeof PrestacoesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestacoes/$id/editar': {
      id: '/prestacoes/$id/editar'
      path: '/prestacoes/$id/editar'
      fullPath: '/prestacoes/$id/editar'
      preLoaderRoute: typeof PrestacoesIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CondominiosRoute: CondominiosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  HistoricoRoute: HistoricoRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PrestacoesNovaRoute: PrestacoesNovaRoute,
  PrestacoesIndexRoute: PrestacoesIndexRoute,
  UsuariosIndexRoute: UsuariosIndexRoute,
  PrestacoesIdEditarRoute: PrestacoesIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
